server:
      port: 8870
spring:
  application:
    name: leasing-sys-service

eureka:
  port:
    8800
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/