server:
  port: 8810
spring:
  application:
    name: leasing-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: calculate-service
        uri: lb://leasing-calculate-service
        predicates:
        - Path=/leasing/calculate/**
      - id: custom-service
        uri: lb://leasing-custom-service
        predicates:
        - Path=/leasing/custom/**
      - id: sys-service
        uri: lb://leasing-sys-service
        predicates:
        - Path=/leasing/sys/**
      - id: customer-service
        uri: lb://leasing-customer-service
        predicates:
        - Path=/leasing/customer/**
      - id: menu-service
        uri: lb://leasing-menu-service
        predicates:
        - Path=/leasing/menu/**
eureka:
  port:
    8800
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/