server:
      port: 8880
spring:
  application:
    name: leasing-sys-service
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    mapping-resources:
logging:
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  path: E:/log/seller.log
  level:
    root: info
eureka:
  port:
    8800
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/