server:
  port: 8810
spring:
  application:
    name: leasing-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: calculate-service
        uri: lb://leasing-calculate-service
        predicates:
        - Path=/leasing/calculate/**
      - id: custom-service
        uri: lb://leasing-custom-service
        predicates:
        - Path=/leasing/custom/**
      - id: contract-service
        uri: lb://leasing-contract-service
        predicates:
        - Path=/leasing/contract/**
eureka:
  port:
    8800
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/